let b = 2

try {
    let a = 2 + b
    console.log(a)
} catch (error) {
    console.log(error)
}


console.log('alo')